name: Release Please

on:
  workflow_dispatch:  # Manual trigger only to avoid duplicate runs

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go
          
      # If release was created, update VERSION file
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        
      - if: ${{ steps.release.outputs.release_created }}
        name: Update VERSION file
        run: |
          echo "${{ steps.release.outputs.version }}" > VERSION
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add VERSION
          git commit -m "chore: update VERSION to ${{ steps.release.outputs.version }}"
          git push